name = "nssa-topfac"
main = "src/index.js"
compatibility_date = "2025-08-05"

# 环境变量
[vars]
ENVIRONMENT = "production"
CORS_ORIGINS = "https://topfac.nssa.io,https://localhost:3000"

# 绑定配置 (D1 数据库已在下方配置)

# KV 存储 (可选，用于缓存)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "nssa-topfac-db"
database_id = "edbcc68e-ac43-43a7-abcf-bed4a466be07"

# 静态资源配置 (用于前端文件)
[assets]
directory = "./public"
binding = "ASSETS"
